### PR TITLE
feat: allow overwriting of endpoints (for local/docker dev)

### PR DESCRIPTION
**Pull request by GRBurst**
This basically allows overwriting all necessary endpoints:
```
        host_endpoint: str = None,
        api_endpoint: str = None,
        auth_endpoint: str = None,
```

This is necessary if you want to connect from within a docker container to a locally running nocode (on localhost).
Is this fine or should we app a post-/prefix like `host_endpoint_overwrite`?

Signed-off-by: GRBurst <GRBurst@protonmail.com>

### CODE REVIEW

**Comment by GRBurst** [comment]
FYI: Having fully qualified overwrites of the endpoints seems to be the easiest solution that offers enough flexibility. Tried it with "smaller" overwrites like protocol or port definitions before, but turned out to be more complicated in the usage

**Review by BayooG — APPROVED** [review]
LGTM

**Review by cornerman — APPROVED** [review]
LGTM. I guess, you left the `host` parameter for backwards compatability? Should we remove or warn when it is used? Then we can remove it later.

**Comment by GRBurst** [comment]
> LGTM. I guess, you left the `host` parameter for backwards compatability? Should we remove or warn when it is used? Then we can remove it later.

I would do it in a follow up pr when we are utilizing the `app_config.json` more

**Pull request merged**
